# Generated by Django 2.2.4 on 2019-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_customer_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.IntegerField(default=1),
        ),
    ]
